---
sidebar: sidebar
permalink: fixed-issues.html
keywords: fixed issues, release notes, fixes, gfc, global file cache
summary: See what issues have been fixed in BlueXP edge caching.
---

= Fixed issues in BlueXP edge caching
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
See what issues have been fixed in BlueXP edge caching.

== 1 August 2023 (version 2.3)

* The following Optimus Configuration UI fixes have been made:
** Shows meaningful information for errors instead of exception strings.
** Displays the license expiry date correctly instead of any default values. 
** Displays the username/password fields correctly when SSL is enabled in the UI.
** Does not become unresponsive when an unreachable GFC Core is configured on the Optimus UI Edge configuration tab.
** Enables you to select multiple cache/edge names from the Edge dropdown List.
* The License Summary information is displayed correctly while viewing expired and non-expired licenses.
* Fixed the TappN service to restart only when the configuration is updated successfully.
* Added a refresh button in the first-time wizard to show the Edge count.
* SSL information is now shown in the first-time wizard summary page.
* Added infrastructure in Tum to allow configuring minidump timeouts and to perform a minidump correctly.
* Optimus and the first-time wizard will show the appropriate license count and will show an exception when the license count becomes zero.
* Optimus PSM now displays an appropriate error message when the Edge server name entered is empty.
* Fixed an issue where pre-population jobs are not correctly applied to multiple cache names in Optimus PSM.
* The License Manager configuration is enhanced to display hard errors instead of soft errors.
* The Zoura registration UI will show an error if it's already configured.
* Optimus UI and Optimus PSM now show CPU and memory requirements of 8 CPU and 32 GB RAM respectively.

== 27 March 2023 (version 2.2)

* Fixed an issue of converting the time format of running a pre-population job for 'last modification time' option.
* Fixed an issue related to parsing of file transfer and passing it on to Cloud Insights service.
* Edge Sync of files across all subscribers is reconnected automatically when there is a disconnect with the publisher.
* Fixed pre-population job execution on an Edge if its connected to multiple Cores.
* Optimus UI now shows the connected Edge list on a publisher that participates in Edge Sync functionality.

== 24 October 2022 (version 2.1)

* An additional validation of the GFC subscription number is performed during licensing configuration.
* GFC added support to extend the license for a specific duration for Zuora-based licenses. Contact GFC support.
* Added a 15 sec delay before writing a minidump after a crash. Also added a timer to monitor the minidump and forcibly exit the process if the dump does not complete in 60 secs. These minor enhancements will help for better analysis.
* Removed individual file transfer information propagation to Cloud Insights, but added File transfer summary information propagation to Cloud Insights. This reduces enormous load on CI.
* Fixed data and metadata ingestion into Cloud Insights. This enables for data visualization CI.
* Fixed the Optimus Configuration UI to not hang while clicking the "Registering instance to CI" button. 
* Fixed an issue where the Tservice monitor is left manual during initial configuration. 
* Fixed minor bugs in the GFC CI Agent CLient service.

== 25 July 2022 (version 2.0)

* Optimus is enhanced by adding boundary limits to date/time parameters for pre-population job addition configuration.
* Optimus PSM now shows the correct CPU details in system pre-requisition details.
* Fixed an exception in the UI during Edge Sync configuration between entering coordinator details and clicking the Refresh button.
* Enhanced the Optimus UI to enable/disable the Edge Sync feature on the edge.
* Fixed the date range issue in License Server Manager for Zuora License Aggregator.
* Fixed the Optimus PSM to show Lease Count information.
* Fixed License Management Server's logic on configuration updater during an upgrade.

== 23 June 2022 (version 1.3.1)

* Upon upgrade, the correct version of Microsoft re-distributable is not installed correctly and as a result Tum does not start. The GFC installer has been fixed to install the correct version re-distributable.
* The GFC License Manager Service (LMS) now updates the configuration information, instead of overwriting it.
* The Configuration UI now binds to the correct System.net.http dll during the upgrade process.

== 19 May 2022 (version 1.3.0)

* The Configuration UI page for Edge Sync functionality is updated.
* Fixed an issue when adding pre-population jobs for multiple Edges at the same time via PowerShell cmdlets.
* Fixed a display issue in LMS Web UI that displays the NetApp subscription.
* The LMS configuration PowerShell script now uses TLS 1.2.
* Fixed an issue in TappN (pre-population service) and enabled it to continue executing the job, despite transient disconnections or Tum restarts.
* The TappN pre-population service is updated to skip fetching files if free cache space falls below the lower threshold value.
* Fixed an issue in the License Manager Server Service (LMS) while writing a trace log.
* The Logging infrastructure for Tum is updated to be more scalable with high performance.
