settings:
  name: BlueXP edge caching
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
sidebar:
  entries:
    - title: BlueXP edge caching docs
      url: /index.html
    - title: Release notes
      entries:
        - title: What's new
          url: /whats-new.html
        - title: Fixed issues
          url: /fixed-issues.html
    - title: Get started
      entries:
        - title: Learn about BlueXP edge caching
          url: /concept-gfc.html
        - title: BlueXP edge caching prerequisites
          url: /concept-before-you-begin-to-deploy-gfc.html
        - title: Deploy and license BlueXP edge caching
          url: /task-gfc-getting-started.html
        - title: BlueXP edge caching Edge prerequisites
          url: /download-gfc-resources.html
        - title: Deploy BlueXP edge caching Edge
          url: /task-deploy-gfc-edge-instances.html
    - title: Use BlueXP edge caching
      entries:
        - title: End-user training
          url: /concept-gfc-enduser-training.html
        - title: Additional information
          url: /reference-gfc-additional-information.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: BlueXP
  repo: bluexp-family
homepage:
  tiles:
    - title: Get started
      links:
        - title: Learn about BlueXP edge caching
          url: concept-gfc.html
        - title: What's New
          url: whats-new.html
        - title: Limitations
          url: concept-gfc.html#limitations
    - title: Deploy components
      links:
        - title: Deploy Cloud Volumes ONTAP as the storage platform
          url: task-gfc-getting-started.html#deploy-cloud-volumes-ontap-as-your-storage-platform
        - title: Deploy the BlueXP edge caching Management Server and Core
          url: task-gfc-getting-started.html#enable-bluexp-edge caching-in-your-working-environment
        - title: Deploy BlueXP edge caching Edge instances
          url: task-deploy-gfc-edge-instances.html
    - title: Train users
      links:
        - title: End-user training
          url: concept-gfc-enduser-training.html
    - title: Blogs & community
      links:
        - title: NetApp Community
          url: https://community.netapp.com/t5/BlueXP-and-Services/ct-p/CDS
        - title: BlueXP blog
          url: https://bluexp.netapp.com/blog
        - title: Cloud webinars
          url: https://bluexp.netapp.com/events
    - title: Other resources
      links:
        - title: BlueXP Edge Caching use cases
          url: https://bluexp.netapp.com/global-file-cache
