settings:
  name: BlueXP edge caching
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
sidebar:
  entries:
    - title: BlueXP edge caching docs
      url: /index.html
    - title: Release notes
      entries:
        - title: What's new
          url: /whats-new.html
        - title: Fixed issues
          url: /fixed-issues.html
    - title: Get started
      entries:
        - title: Learn about BlueXP edge caching
          url: /concept-gfc.html
        - title: BlueXP edge caching prerequisites
          url: /concept-before-you-begin-to-deploy-gfc.html
        - title: Deploy and license BlueXP edge caching
          url: /task-gfc-getting-started.html
        - title: BlueXP edge caching Edge prerequisites
          url: /download-gfc-resources.html
        - title: Deploy BlueXP edge caching Edge
          url: /task-deploy-gfc-edge-instances.html
    - title: Use BlueXP edge caching
      entries:
        - title: End-user training
          url: /concept-gfc-enduser-training.html
        - title: Additional information
          url: /reference-gfc-additional-information.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: BlueXP
  repo: bluexp-family
