---
sidebar: sidebar
permalink: whats-new.html
keywords: what's new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, gfc, global file cache
summary: Learn what's new in BlueXP edge caching.
---

= What's new with BlueXP edge caching
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Learn what's new in BlueXP edge caching.

// tag::whats-new[]
== 1 August 2023 (version 2.3)

This release fixes the issues described in the https://docs.netapp.com/us-en/bluexp-edge-caching/fixed-issues.html[Fixed Issues]. Updated software packages are available at https://docs.netapp.com/us-en/bluexp-edge-caching/download-gfc-resources.html#download-required-resources[this page].

== 5 April 2023 (version 2.2)

This release provides the new features listed below. It also fixes the issues described in the https://docs.netapp.com/us-en/bluexp-edge-caching/fixed-issues.html[Fixed Issues].

=== Support for Global File Cache on Cloud Volumes ONTAP systems deployed in Google Cloud

A new "Edge Cache" license is available when deploying a Cloud Volumes ONTAP system in Google Cloud. You are entitled to deploy one Global File Cache Edge system for each 3 TiB of purchased capacity on the Cloud Volumes ONTAP system.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html#packages[Learn more about the Edge Cache license package.]

=== The setup wizard and GFC Configuration UI are enhanced to perform NetApp license registration

=== Enhanced Optimus PSM to configure Edge Sync functionality

== 24 October 2022 (version 2.1)

This release provides the new features listed below. It also fixes the issues described in the https://docs.netapp.com/us-en/bluexp-edge-caching/fixed-issues.html[Fixed Issues].

=== Global File Cache is now available with any number of licenses

The previous minimum requirement of 10 licenses, or 30 TB of storage, has been removed. One Global File Cache license will be issued for every 3 TB of storage.

=== Support has been added for using an offline License Management Server

An offline, or dark site, License Management Server (LMS) is most useful when the LMS does not have an internet connection for license validation with license sources. An internet connection and connection to license source is required during initial configuration. Once configured, the LMS instance can become dark. All Edges/Cores should have a connection with LMS for continuous validation of licenses.

=== Edge instances can support additional concurrent users

A single Global File Cache Edge instance can serve up to 500 users per dedicated physical Edge instance, and up to 300 users for dedicated virtual deployments. The maximum number of users used to be 400 and 200, respectively.

=== Enhanced Optimus PSM to configure Cloud Licensing

=== Enhanced the Edge Sync feature in Optimus UI (Edge Configuration) to show all connected clients
// end::whats-new[]

== 25 July 2022 (version 2.0)

This release provides the new features listed below. It also fixes the issues described in the https://docs.netapp.com/us-en/bluexp-edge-caching/fixed-issues.html[Fixed Issues].

=== New capacity-based licensing model for Global File Cache through the Azure Marketplace

A new "Edge Cache" license has the same capabilities as the "CVO Professional" license, but it also includes support for Global File Cache. You'll see this option when deploying a new Cloud Volumes ONTAP system in Azure. You are entitled to deploy one Global File Cache Edge system for each 3 TiB of provisioned capacity on the Cloud Volumes ONTAP system. A minimum of 30 TiB should be provisioned. The GFC License Manager Service has been enhanced to provide capacity-based licensing.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html#capacity-based-licensing[Learn more about the Edge Cache license package.]

=== Global File Cache is now integrated with Cloud Insights

NetApp Cloud Insights (CI) gives complete visibility into your infrastructure and applications. Global File Cache is now integrated with CI to provide complete visibility of all edges and cores; monitoring processes running on the instances. Various Global File Cache metrics are pushed to CI to provide a complete overview on the CI dashboard. See Chapter 11 in the https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%202.1.0%20User%20Guide.pdf[NetApp Global File Cache User Guide^]

https://cloud.netapp.com/cloud-insights[Learn more about Cloud Insights.]

=== License Management Server has been enhanced to operate in very restrictive environments

During license configuration, the License Management Server (LMS) should have access to the internet to collect the licensing details from NetApp/Zuora. Once the configuration is successful, the LMS can continue to work in offline mode and provide licensing capabilities despite being in restrictive environments.

=== The Edge Sync UI in Optimus has been enhanced to show the list of connected clients on a coordinator Edge
